version: "2"
services:
 jenkins-master:
    build: jnk
    ports:
    - "8083:8080"
    expose:
    - "8080"
    volumes: 
    - /var/jenkins_home
 nexus:
    build: nxs
    ports:
     - "8089:8081"
    volumes:
    - /nexus-data
 docker-slave:
    build: docker-slave
    environment:
      - JENKINS_MASTER_SERVER=jenkins-master
      - JENKINS_MASTER_PORT=8083
      - SLAVE_NAME=docker-slave
    entrypoint: "sh startup.sh"
    depends_on:
      - jenkins-master